const schoolsTypes = {
    ADD_NEW_SCHOOL_START: "ADD_NEW_SCHOOL_START",
    FETCH_SCHOOLS_START: "FETCH_SCHOOLS_START",
    SET_SCHOOLS: "SET_SCHOOLS",
    DELETE_SCHOOL_START: "DELETE_SCHOOL_START",
    FETCH_SCHOOL_START: "FETCH_SCHOOL_START",
    SET_SCHOOL: "SET_SCHOOL"
};

export default schoolsTypes;