const shippingTypes = {
    FETCH_SHIPPING_ZONES_START: 'FETCH_SHIPPING_ZONES_START',
    SET_SHIPPING_ZONES: 'SET_SHIPPING_ZONES',
    SET_SHIPPING_ADDRESS: 'SET_SHIPPING_ADDRESS',
    UPDATE_SHIPPING_ZONE_START: 'UPDATE_SHIPPING_ZONE_START',
    UPDATE_SHIPPING_ZONE_FINISH: 'UPDATE_SHIPPING_ZONE_FINISH',
};

export default shippingTypes;