const ordersTypes = {
    PREPARE_ORDER_START: 'PREPARE_ORDER_START',
    SET_PREPARED_ORDER: 'SET_PREPARED_ORDER',
    CONFIRM_PAYMENT_START: 'CONFIRM_PAYMENT_START',
    UPDATE_PAYMENT_STATUS_START: 'UPDATE_PAYMENT_STATUS_START',
};

export default ordersTypes;