const ordersTypes = {
    PREPARE_ORDER_START: 'PREPARE_ORDER_START',
    CONFIRM_PAYMENT_START: 'CONFIRM_PAYMENT_START',
    UPDATE_PAYMENT_STATUS_START: 'UPDATE_PAYMENT_STATUS_START',
    FETCH_ORDERS_START: "FETCH_ORDERS_START",
    SET_ORDERS: "SET_ORDERS",
    FETCH_ORDER_START: "FETCH_ORDER_START",
    SET_ORDER: "SET_ORDER",
    COMPLETE_ORDER_START: "COMPLETE_ORDER_START",
    SET_ORDER_COMPLETE: "SET_ORDER_COMPLETE",
    UPDATE_ORDER_START: 'UPDATE_ORDER_START',
    SET_ERROR: 'SET_ERROR'

};

export default ordersTypes;