const subjectsTypes = {
    ADD_NEW_SUBJECT_START: "ADD_NEW_SUBJECT_START",
    FETCH_SUBJECTS_START: "FETCH_SUBJECTS_START",
    SET_SUBJECTS: "SET_SUBJECTS",
    DELETE_SUBJECT_START: "DELETE_SUBJECT_START",
    FETCH_SUBJECT_START: "FETCH_SUBJECT_START",
    SET_SUBJECT: "SET_SUBJECT"
};

export default subjectsTypes;